### PR TITLE
Make beemovie.txt load bearing

### PR DESCRIPTION
**Pull request by duplexsystem**
ensure game crashes if beemovie.txt is not present. this was intended behavior

### CODE REVIEW

**Review by ENDERZOMBI102 — CHANGES_REQUESTED** [review]
this will _not_ make the game crash if it is not present

**Comment by Tyfyter** [comment]
All this does is not log that beemovie.txt is missing, you need to remove the try & catch blocks entirely.

**Comment by ENDERZOMBI102** [comment]
wrap it in a `doSafely( () -> { $TRY_BODY } );` to get the desired behavior

**Comment by duplexsystem** [comment]
fixed

**Pull request merged**
