### PR TITLE
Added a few new ores

### PR DESCRIPTION
**Pull request by C10udburst**

### CODE REVIEW

**Comment by valoeghese** [comment]
did you just autogenerate files lmfao

**Comment by C10udburst** [comment]
> did you just autogenerate files lmfao

No, obviously I coded 100 new ores by hand lol

**Comment by anatom3000** [comment]
> No, obviously I coded 100 new ores by hand lol

Let me see if this even build :concern:

**Comment by anatom3000** [comment]
How many characters did you added ?

**Comment by C10udburst** [comment]
> How many characters did you added ?

It shows on the top 23k lol

**Comment by anatom3000** [comment]
Congratulations, you've just increased the jar size by 2 Mb 🤔

**Comment by anatom3000** [comment]
Now let's get this running in prod

**Comment by C10udburst** [comment]
> Congratulations, you've just increased the jar size by 2 Mb 🤔

I mean there are more than 300 new textures soo..

**Comment by SekoiaTree** [comment]
Personally, I wouldn't merge this until there's a couple less files lol, because 99% of these are just empty classes which shouldn't be a thing

**Pull request merged**
