### PR TITLE
Create x

### PR DESCRIPTION
**Pull request by lnee94**
log program

### CODE REVIEW

**Comment by MattiDragon** [comment]
Does this work on all operating systems?

**Comment by ENDERZOMBI102** [comment]
i don’t think mac uses X
windsows foesn’t use X
so no

**Comment by MattiDragon** [comment]
Should we add a rule that says it has to be designed to work on all systems? Of course we can't test that, but if you do low level stuff then at least check.

**Comment by ENDERZOMBI102** [comment]
yeah, good idea

**Comment by MattiDragon** [comment]
Can you PR? Got to go.

**Comment by ENDERZOMBI102** [comment]
from phone

**Comment by MattiDragon** [comment]
Yeah. I fixed AnnotationExclutionStrategy from the phone.

**Comment by ENDERZOMBI102** [comment]
no, i’m from phone, i cant make PRs

**Comment by MattiDragon** [comment]
You can on the website. The app is very limited

**Comment by ENDERZOMBI102** [comment]
the website isn’t interactive from ios 12

**Comment by MattiDragon** [comment]
Odd. I'll do it myself then

**Pull request closed without merging**
