### PR TITLE
Mess up 3d graphics

### PR DESCRIPTION
**Pull request by JFronny**
Though I tried to keep it somewhat playable

### CODE REVIEW

**Comment by anatom3000** [comment]
Could you send a pic quickly ?

**Comment by anatom3000** [comment]
Of the 3d graphics, not nudes

**Comment by JFronny** [comment]
image

**Comment by anatom3000** [comment]
:concern:

**Comment by anatom3000** [comment]
But ok, you can PR anything 😏

**Comment by anatom3000** [comment]
I feel like this mod could become a challenge 😆

**Comment by ExoPlant** [comment]
With this PR, I am unable to even test my code.

**Pull request merged**
