### PR TITLE
Replace all sounds with "blyat"

### PR DESCRIPTION
**Pull request by JFronny**
yes

### CODE REVIEW

**Comment by anatom3000** [comment]
Good job, you made the first PR of this project !

**Comment by anatom3000** [comment]
@JFronny it crashes on startup due to the mixin I'm gonna push a temporary fix (just remove the mixin from `gwwhit.mixin.json`, didn't remove any code)

**Comment by JFronny** [comment]
It shouldn't do that, I tested it and it worked fine

**Comment by anatom3000** [comment]
Strange... Have you tried in a normal (non-dev) environment ?

**Comment by JFronny** [comment]
OK, I have confirmed that it fails due to not remapping the target method (even though it should). Since remapping is also an issue in my latest PR I think it is likely that something is wrong with mixin here (or I am just stupid)

**Pull request merged**
