### PR TITLE
Added toggle commands for most client-side things

### PR DESCRIPTION
**Pull request by LordDeatHunter**

### CODE REVIEW

**Comment by anatom3000** [comment]
The build actions fail, does it work on your machine ?

**Comment by anatom3000** [comment]
look here : https://github.com/anatom3000/GuessWhatWillHappenInThis/pull/15/checks?check_run_id=2436326720

**Comment by LordDeatHunter** [comment]
It seems it's a merge conflict issue caused by some of the new PRs. I'll fix it in a sec

**Comment by LordDeatHunter** [comment]
It should be good now.

**Pull request merged**
