### PR TITLE
enhance user experience with README.md

### PR DESCRIPTION
**Pull request by Yoghurt4C**
`Fabric mod where anyone can PR anything, concerning or not (Unless it's too concerning). I'll merge everything as soon as it works.`

### CODE REVIEW

**Comment by anatom3000** [comment]
no.

**Comment by Yoghurt4C** [comment]
:sob:

**Comment by anatom3000** [comment]
youre supposed to mess with Minecraft, not mess with our README

**Comment by anatom3000** [comment]
its not even an improvement

**Comment by Yoghurt4C** [comment]
enhancement does not always correlate with improvement though :)

**Comment by anatom3000** [comment]
still

**Pull request closed without merging**
