### PR TITLE
Tiny cleanup of the ores

### PR DESCRIPTION
**Pull request by C10udburst**
https://user-images.githubusercontent.com/18114966/119619523-60e99700-be04-11eb-9ccb-c675f49e9533.mp4

### CODE REVIEW

**Comment by anatom3000** [comment]
but why putting this video ?

**Comment by anatom3000** [comment]
since i merged #37 there are too many conflicts. cant merge sorry

**Comment by C10udburst** [comment]
image
welp i cant resolve this myself

**Comment by anatom3000** [comment]
should i close ?

**Pull request merged**
