### PR TITLE
Disallow system hacking

### PR DESCRIPTION
**Pull request by SekoiaTree**
Keyloggers, backdoors and viruses aren't allowed anymore, and editing the readme is also not allowed

### CODE REVIEW

**Comment by SekoiaTree** [comment]
Technically, since this doesn't change any java code, it does build

**Comment by anatom3000** [comment]
@SekoiaTree remove the part about you please

**Comment by anatom3000** [comment]
nothing against you, it's just that i feel like the project should stay made by the community, not managed by some people

**Comment by SekoiaTree** [comment]
fair enough lol

**Comment by anatom3000** [comment]
i see ;) but even if i merge quickly, it doesn't mean that i don't stay aware about what has been changed

**Pull request merged**
