### PR TITLE
Command line updater

### PR DESCRIPTION
**Pull request by MattiDragon**
### Key features
- Download files from directly modrinth api
- Automatic picker for best version

### Key concerns
- Can't be used inside a IDE since it requires a jar to be present
- Crashes with a uncaught exception if anything is wrong
- Use gradle shadow plugin to shadow gson
- Due to using the gradle shadow plugin the main jar is now `GuessWhatWillHappenInThis-1.2.0-all.jar`

PS. I also added a option to make all blocks slippery

### CODE REVIEW

**Comment by ENDERZOMBI102** [comment]
why do you shadow gson? minecraft alredy uses it. its already in the enviroment...

**Comment by MattiDragon** [comment]
> why do you shadow gson? minecraft alredy uses it. its already in the enviroment...

The updater runs in the command line. All I have is the mod jar and the jdk. I can't even use the include feature of loom + floader because I run without them.

**Comment by ENDERZOMBI102** [comment]
just doing implementation should work then?

**Comment by MattiDragon** [comment]
Implementation means it's compiled and run with the dependecy. It doesn't mean that it's included in the final jar

**Comment by ENDERZOMBI102** [comment]
> Implementation means it's compiled and run with the dependecy. It doesn't mean that it's included in the final jar

ohhhh right, i forgot that...

**Pull request merged**
