### PR TITLE
refactor codebase

### PR DESCRIPTION
**Pull request by TehcJS**

### CODE REVIEW

**Comment by ENDERZOMBI102** [comment]
omfg

**Comment by TehcJS** [comment]
do you like the new documentation?

**Comment by ENDERZOMBI102** [comment]
i can't even view the files.... they're over 10mb....

**Comment by TehcJS** [comment]
> i can't even view the files.... they're over 10mb....

what's wrong, big boy? never had contributors?

**Review by TehcJS — COMMENTED** [review]
i approve

**Comment by C10udburst** [comment]
sketchy diff ngl

**Pull request closed without merging**
