### PR TITLE
wewewewewewewe

### PR DESCRIPTION
**Pull request by lnee94**
wewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewewe

### CODE REVIEW

**Comment by C10udburst** [comment]
Doesn't work on windows 🥱

**Comment by anatom3000** [comment]
> Doesn't work on windows 🥱 

Why?

**Comment by anatom3000** [comment]
~~just use Linux~~

**Comment by C10udburst** [comment]
> > Doesn't work on windows 🥱
> 
> Why?

Because windows uses `gradlew.bat`.

**Pull request closed without merging**
