### PR TITLE
Add Bee Paintings

### PR DESCRIPTION
**Pull request by Dragonoidzero**
:bee:

### CODE REVIEW

**Comment by SekoiaTree** [comment]
why did you censor one but not the others

**Comment by Dragonoidzero** [comment]
:bee:

**Review by Platymemo — APPROVED** [review]

**Review by LePichu — APPROVED** [review]
Succubus Bed Best Bee.

**Review by Leo40Git — CHANGES_REQUESTED** [review]
Give credit to the original artists somewhere and I'll approve this.

**Comment by valoeghese** [comment]
this is too concerning

**Comment by anatom3000** [comment]
also there are conflicts, could you resolve them ?

**Pull request closed without merging**
